language: python
python: "2.7"
install:
    - "pip install coveralls"
script: 
    - make validate
    - git fetch origin master:refs/remotes/origin/master # https://github.com/edx/diff-cover#troubleshooting
    - make diff.report
after_success:
    - coveralls
